#!/bin/bash

# This script must be run using 'make test'.

set -e

for test in ../../tests/*.txt; do
    test=$(basename "$test" .txt) # get basename without .txt
    make --no-print-directory PKG=$test test-pkg
    echo
done

echo "All tests were successful"
