#!/bin/bash

# This script must be run using 'make test'.

set -e

for test in ../../tests/*.txt; do
    test=$(basename "$test" .txt) # get basename without .txt
    make --no-print-directory build/test/$test.txt
    diff -u ../../tests/$test.txt build/test/$test.txt
    echo OK
    echo
done

echo "All tests were successful"
